fail astyle job if there exists files should be formatted
Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -28,7 +28,8 @@ jobs:
     - uses: cachix/install-nix-action@v25
       with:
         nix_path: nixpkgs=${{ steps.nixpkgs.outputs.nixpkgs }}
-    - uses: workflow/nix-shell-action@v3.3.0
+    - name: Prepare nix dev shell
+      uses: workflow/nix-shell-action@v3.3.0
       with:
         flakes-from-devshell: true
         script: |
@@ -38,4 +39,10 @@ jobs:
       with:
         flakes-from-devshell: true
         script: |
-          astyle $(git ls-files "*.c" "*.h") --options=.astylerc --dry-run --formatted
+          err=$(astyle $(git ls-files "*.c" "*.h") --options=.astylerc --dry-run --formatted)
+          if [[ ${#err} != 0 ]]; then
+            echo "$err" | awk '{split($0,a);print a[2]}' | while IFS= read -r file; do
+              echo "::error file={"$file"},title={checking}::Formatted $file"
+            done
+            exit 1
+          fi
